---
- hosts: localhost
  gather_facts: no
  become : yes
  vars_files:
    - variables.yml
  vars:
    mysql_password : "{{mysql_password}}"
    user_name : "{{mysql_user}}"
    email : "{{email_username}}"
    email_password : "{{email_password}}"
  tasks:
  - name : Copy db.properties.template
    template : 
      src : /file-templates/db.properties.template
      dest : /var/lib/jenkins/workspace/iTrust/iTrust2/src/main/java/db.properties
      force : no
      remote_src : yes
    become: true
  - name : Copy email.properties.template
    template : 
      src : /file-templates/email.properties.template
      dest : /var/lib/jenkins/workspace/iTrust/iTrust2/src/main/java/email.properties
      force : no
      remote_src : yes
    become: true