---
- hosts: localhost
  gather_facts: no
  become : yes
  vars_files:
    - /home/vagrant/variables.yml
  tasks:
  - name: Run python script to configure AWS instance
    script: provisionAws.py
    args:
      executable: python3
  - name: sleep for 240 seconds and continue with play
    wait_for: timeout=240
  - name: Change permission of key
    file:
      path: /home/vagrant/DeployMilestone.pem
      mode: 0600