- hosts: jenkins-srv
  gather_facts: false
  become: true
  vars_files:
    - /ansible_srv/variables.yml
  tasks:
    - name: create jobs directory
      file:
        path: /jobs
        state: directory

    - name: Place checkbox-build job file inside /jobs 
      copy:
        src: /ansible_srv/jobs/checkbox-build.yml
        dest: /jobs/
      become: true   

    - name: Put checkbox-repo git link in the jobs file
      lineinfile : 
        path : /jobs/checkbox-build.yml
        state : present
        regex : 'git_url'
        line : "          url: {{checkbox_repo}}"


    - name: Clone checkboxio git repo into /home/vagrant/
      git:
        repo: '{{checkbox_repo}}'
        dest: /home/vagrant/checkboxio/
        clone: yes
        update: yes  
      become: true

    - name: uninstall requests
      pip: 
        name: requests
        state: absent
        
    - name: install requests
      pip:
        name: requests 
        state: present    


    - name: create jenkins job
      command: jenkins-jobs update jobs
      args:
        chdir: /
      become: true   
